### ISSUE TITLE
Which template image?

### ISSUE THREAD

**Issue by manuels** [albertlai/deep-style-transfer#1]
Very nice project! But there is something that is not quite clear to me.
In your example you apply the Van Gogh style (starry.jpg) to the photo (sf.jpg) and output the result (styled.jpg).
The command line tool

    python style.py --input=path_to_image.jpg --output=your_output_file.jpg

allows to specify `--input` (sf.jpg?) and `--output` (styled.jpg?), but how do you specify that it should use starry.jpg as style?

**Comment by albertlai** [comment]
The style.py script defaults to a pretrained model file in data/vg-30.pb. In order to style using another reference image, you'd have to run the train.py script on another image then use the model once it is trained. I'll update the readme to be more clear!

**Comment by manuels** [comment]
Great, thanks!
