### ISSUE TITLE
can you open source the C++ code either?

### ISSUE THREAD

**Issue by michaeldengchangshun** [albertlai/deep-style-transfer#2]
it would help the others to evaluate the application. thanks a lot.

**Comment by albertlai** [comment]
What c++ code are you referring to?

**Comment by michaeldengchangshun** [comment]
@albertlai: the C++ source code which used to be called by Java. Thanks.

**Comment by albertlai** [comment]
This project is entirely in tensorflow, using the tensorflow Python library
