### ISSUE TITLE
Trouble styling based on Trained model

### ISSUE THREAD

**Issue by gaylejj** [albertlai/deep-style-transfer#3]
I'm trying to style an image based on a model I trained, but keep getting a Tensorflow error about not being able to find the Tensor.

![transfererror](https://cloud.githubusercontent.com/assets/3372219/22564986/6eaa4292-e93b-11e6-92d0-f0d5d7cf254f.JPG)

I tried specifying the model file in the arguments as --model_file=./diving.pb (with file in my main directory), as well as placing it in the data folder and replacing the default argument in style.py with my file name. I get the same error every time. Is there something I am missing when specifying the file?

**Comment by albertlai** [comment]
The script expects the namespace for the model to be the same as the filename for the .pb file - sorry this was not anywhere in the README! The default model name is "model" so if you didn't specify a name when training, naming the file model.pb ought to work. 

I will put up the script I used to export pb files so hopefully that won't be an issue  after I clean it up a bit

**Comment by gaylejj** [comment]
Ahh gotcha. I'll try again in the morning. I had renamed the file, but not to what I specified in the python command.

**Comment by albertlai** [comment]
OK let me know if it works!

**Comment by gaylejj** [comment]
So that worked for finding the Tensor, but now I'm getting a new error, which looks like a matrix error. 

![snip2](https://cloud.githubusercontent.com/assets/3372219/22599155/ae6e44b4-e9ea-11e6-8b76-31da03e650df.JPG)

**Comment by albertlai** [comment]
The styling script expects a tensor of shape 1 x image_height x image_width x 3 but the training script has a shape batch_size x image_height x image_width x 3 - when you freeze the pb file you'll have to make sure when you load the StyleTransfer model you set the batch size to 1 so something like

`            train_model = style_transfer.StyleTransfer(                                                                                                                         
                is_training=False, batch_size=1,                                                                                                                   
                image_h=args.image_h, image_w=args.image_w, model=args.generator)  `

**Comment by gaylejj** [comment]
Ok, I think I understand. So when I set the training, with train.py I need to specify the batch-size of 1?

**Comment by gaylejj** [comment]
Alright, getting closer...

Now running the command python style.py --model_file=./diving.pb --input=./puppy.jpg --output=./puppy_diving.jpg after training with python train.py --data_dir=./val2014 --texture=diving.jpg --model_name=diving --batch_size=1, I get the following

![snip3](https://cloud.githubusercontent.com/assets/3372219/22604569/11f7e1be-ea01-11e6-96fc-4ea4ffa2d53e.JPG)

Thanks again for all your help, this is a super cool project!

**Comment by albertlai** [comment]
I uploaded my export script - can you try it out? You run it with

python export.py input_dir=your-models-path

and it outputs a .pb file in that path
